[general]
import = [
    "C:\\Users\\User\\AppData\\Roaming\\alacritty\\themes\\themes\\kanagawa_dragon.toml",
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[font]
size = 11

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
dimensions = { columns = 150, lines = 40 }
dynamic_padding = true
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 15
y = 15

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Debian",
    "--cd",
    "~"
]